trajectory_server:
  ros__parameters:
    joint_names:
      - left_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - left_arm_yaw_joint
      - left_elbow_pitch_joint
      - left_elbow_yaw_joint
      - left_wrist_pitch_joint
      - left_wrist_roll_joint
      - neck_yaw_joint
      - neck_pitch_joint
      - right_shoulder_pitch_joint
      - right_shoulder_roll_joint
      - right_arm_yaw_joint
      - right_elbow_pitch_joint
      - right_elbow_yaw_joint
      - right_wrist_pitch_joint
      - right_wrist_roll_joint
      - waist_pitch_joint
      - waist_roll_joint
      - waist_yaw_joint
      - left_hip_roll_joint
      - left_hip_yaw_joint
      - left_hip_pitch_joint
      - left_knee_joint
      - left_ankle_pitch_joint
      - left_ankle_roll_joint
      - right_hip_roll_joint
      - right_hip_yaw_joint
      - right_hip_pitch_joint
      - right_knee_joint
      - right_ankle_pitch_joint
      - right_ankle_roll_joint
    kp:
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
      - 1000.0
    kd:
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
      - 20.0
    tolerance: 0.02
